---

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-synapse-admin

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  when: not matrix_k8s_mode | bool
  tags:
    - setup-all
    - setup-synapse-admin

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  when: run_setup | bool and matrix_client_element_enabled | bool and matrix_k8s_mode | bool
  tags:
    - setup-all
    - setup-synapse-admin
    - setup-k8s