---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matrix-synapse-admin
  labels:
    role: matrix-synapse-admin
{{ include "deployment.selector" . | indent 4 }}  
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    role: matrix-synapse-admin
{{ include "deployment.selector" . | indent 4 }}      