---

- block:
    - when: matrix_dimension_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_dimension_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-dimension
    - install-all
    - install-dimension

- block:
    - when: not matrix_dimension_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-dimension

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  when: run_setup | bool and matrix_dimension_enabled | bool and matrix_k8s_mode | bool
  tags:
    - setup-all
    - setup-dimension
    - setup-k8s
