---

- block:
    - when: matrix_ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-ntfy
    - install-all
    - install-ntfy

- block:
    - when: not matrix_ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-ntfy

- block:
    - when: matrix_ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
  tags:
    - self-check

# K8s processing
- block:
    - when: run_setup | bool and matrix_ntfy_enabled | bool and matrix_k8s_mode | bool
      ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  tags:
    - setup-all
    - setup-ntfy

