---

- block:
    - when: matrix_corporal_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_corporal_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-corporal
    - install-all
    - install-corporal

- block:
    - when: not matrix_corporal_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-corporal

- block:
    - when: matrix_corporal_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
  tags:
    - self-check

# K8s processing
- block:
    - when: matrix_corporal_enabled | bool and matrix_k8s_mode | bool
      ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  tags:
    - setup-all
    - setup-corporal

