---
    
- name: Ensure matrix-nginx-proxy helm templates folder exists
  ansible.builtin.file:
    path: "{{ matrix_helm_data_path }}/templates/matrix-nginx-proxy"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: copy matrix-nginx-proxy helm templates
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/k8s/{{ item }}"
    dest: "{{ matrix_helm_data_path }}/templates/matrix-nginx-proxy/"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0660
  loop:
    - "configmap.yaml"
    - "deployment.yaml"
    - "service.yaml"
    - "ingress.yaml"
  when: matrix_k8s_mode | bool

# - name: copy matrix-synapse helm templates
#   ansible.builtin.template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ matrix_user_username }}"
#     group: "{{ matrix_user_groupname }}"
#     mode: 0660
#   with_items:
#     - { src: "{{ role_path }}/templates/k8s/configmap.yaml.j2", dest: "{{ matrix_helm_data_path }}/templates/matrix-synapse/configmap.yaml" }    
#   when: matrix_k8s_mode | bool