---

- block:
    - when: matrix_mailer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-mailer
    - install-all
    - install-mailer

- block:
    - when: not matrix_mailer_enabled | bool and not matrix_k8s_mode | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-mailer
