---
- ansible.builtin.set_fact:
    matrix_k8s_rolename: "{{ role_name|replace('bridge-','')|replace('custom/','')|replace('-','_') }}"

    matrix_nginx_proxy_k8s_svc_replacements: "{{ matrix_nginx_proxy_k8s_svc_replacements + ['matrix-mautrix-whatsapp'] }}"

    matrix_k8s_homeserver_additional_mounts: "{{ matrix_k8s_homeserver_additional_mounts + [{'id': 'matrix-mautrix-whatsapp-registration.yaml', 'src': 'mautrix-whatsapp/config/registration.yaml', 'dest': '/matrix-mautrix-whatsapp-registration.yaml' }] }}"


- ansible.builtin.set_fact:
    matrix_k8s_configuration: "{{ lookup('vars', matrix_k8s_rolename ~ '_k8s_configuration_default')|combine(lookup('vars', matrix_k8s_rolename ~ '_k8s_configuration_custom'), recursive=true) }}"

- ansible.builtin.import_tasks: "roles/custom/matrix-k8s/tasks/subtasks/copy-yaml-files.yml"
