---

- block:
    - when: matrix_mautrix_whatsapp_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_mautrix_whatsapp_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-mautrix-whatsapp
    - install-all
    - install-mautrix-whatsapp

- block:
    - when: not matrix_mautrix_whatsapp_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-mautrix-whatsapp

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  when: matrix_mautrix_whatsapp_enabled | bool and matrix_k8s_mode | bool
  tags:
    - setup-all
    - setup-mautrix-whatsapp
    - setup-k8s