---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matrix-client-element
  labels:
    role: matrix-client-element
{{ include "deployment.selector" . | indent 4 }}  
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    role: matrix-client-element
{{ include "deployment.selector" . | indent 4 }}      