---
- name: Remove base helm templates filder
  ansible.builtin.file:
    path: "{{ matrix_helm_data_path }}/templates"
    state: absent

- name: Configure Playbook to use Kubernetes deployment
  ansible.builtin.set_fact:
    # Disable Postgres at the moment
    matrix_postgres_enabled: false

    # Dynamic DNS not needed in k8s
    matrix_dynamic_dns_enabled: false

    # Systemd shouldn't used when k8s deployment
    matrix_systemd_enable: false

    # do not install docker
    matrix_docker_installation_enabled: false

    # ssl certificate will generated externally
    matrix_ssl_retrieval_method: "none"

    # Disable all self building in k8s case, because not supported
    matrix_client_element_container_image_self_build: false
    matrix_mailer_container_image_self_build: false
    
    # We use a precreated docker image, which have extensions built in
    matrix_synapse_container_image_customizations_enabled: false

    # Disable borg backup in deployments
    matrix_backup_borg_enabled: false

    # Enable S3 Storage
    matrix_synapse_ext_synapse_s3_storage_provider_enabled: true

    # Prepared Image for K8s with extendion files
    matrix_synapse_docker_image: "ghcr.io/swarnat/matrix-synapse-k8s:v1.69.0"

    matrix_nginx_proxy_enabled: true
    matrix_nginx_proxy_https_enabled: false
    matrix_nginx_proxy_http_level_resolver: "{{ matrix_nginx_proxy_k8s_coredns_ip }}"

    matrix_nginx_proxy_proxy_synapse_federation_api_addr_with_container: "{{ matrix_k8s_resource_prefix }}-matrix-synapse.{{ matrix_k8s_namespace }}.svc.cluster.local:{{ matrix_synapse_container_federation_api_plain_port }}"
    matrix_nginx_proxy_proxy_synapse_client_api_addr_with_container: "{{ matrix_k8s_resource_prefix }}-matrix-synapse.{{ matrix_k8s_namespace }}.svc.cluster.local:{{ matrix_synapse_container_client_api_port }}"

    matrix_nginx_proxy_proxy_matrix_federation_api_addr_with_container: "{{ matrix_nginx_proxy_proxy_matrix_federation_api_addr_sans_container }}"
    matrix_nginx_proxy_proxy_matrix_client_api_addr_with_container: "{{ matrix_nginx_proxy_proxy_matrix_client_api_addr_sans_container }}"

    matrix_homeserver_container_url: "http://{{ matrix_k8s_resource_prefix }}-matrix-nginx-proxy.{{ matrix_k8s_namespace }}.svc.cluster.local:12080"
    matrix_homeserver_container_federation_url: "http://{{ matrix_k8s_resource_prefix }}-matrix-nginx-proxy.{{ matrix_k8s_namespace }}.svc.cluster.local:12088"
    
  when: matrix_k8s_mode | bool
