---

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/sanity_check.yml"
  tags:
    - always
    - setup-k8s
  when: "matrix_k8s_mode | bool"

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always
    - setup-k8s
  when: "matrix_k8s_mode | bool"
