---
# Check about matrix_k8s_configuration.database is defined is done in default-processing.yml
- name: "check default database username for {{ var_pefix }}?"
  when: lookup('vars', var_pefix ~ '_database_username', default=var_pefix) == lookup('vars', var_pefix ~ '_k8s_configuration_default').database.default_username
  ansible.builtin.debug:
    msg: "{{ var_pefix ~ '_database_username' }} is default value [{{ var_pefix }}_database_username, {{ var_pefix }}_database_password, {{ var_pefix }}_database_hostname]"  
  tags:
    - setup-k8s
    - setup-all

- when: lookup('vars', var_pefix ~ '_database_hostname', default='matrix-postgres') == 'matrix-postgres' or lookup('vars', var_pefix ~ '_database_hostname', default='matrix-postgres') == ''
  name: Set default K8s postgresql host
  ansible.builtin.set_fact:
    "{{ var_pefix }}_database_hostname": "{{ matrix_k8s_database_host }}"
    "{{ var_pefix }}_database_port": "{{ matrix_k8s_database_port }}"
  tags:
    - setup-k8s
    - setup-all

- when: lookup('vars', var_pefix ~ '_database_username', default=var_pefix) == lookup('vars', var_pefix ~ '_k8s_configuration_default').database.default_username
  name: Set default K8s postgresql credentials
  ansible.builtin.set_fact:
    "{{ var_pefix }}_database_username": "{{ matrix_k8s_database_username }}"
    "{{ var_pefix }}_database_password": "{{ matrix_k8s_database_password }}"
  tags:
    - setup-k8s
    - setup-all

- when: lookup('vars', var_pefix ~ '_database_name', default=var_pefix) == lookup('vars', var_pefix ~ '_k8s_configuration_default').database.default_name
  name: Set default K8s postgresql database name
  ansible.builtin.set_fact:
    "{{ var_pefix }}_database_name": "{{ matrix_k8s_database_database_prefix ~ '_' ~ var_pefix }}"
  tags:
    - setup-k8s
    - setup-all
