---
# This tasks, make some variables optional and set on a default value in kubernetes context
- name: Optimize DB of etherpad
  when: matrix_etherpad_database_hostname == "matrix-postgres"

  ansible.builtin.set_fact:
    matrix_etherpad_database_hostname: '{{ matrix_synapse_database_host }}'
    matrix_etherpad_database_port: '{{ matrix_synapse_database_port }}'


- name: Optimize DB of dimension
  when: matrix_dimension_database_hostname == "matrix-postgres"

  ansible.builtin.set_fact:
    matrix_dimension_database_hostname: '{{ matrix_synapse_database_host }}'
    matrix_dimension_database_port: '{{ matrix_synapse_database_port }}'    


- name: Optimize DB of bot-buscarron
  when: matrix_bot_buscarron_database_hostname == "matrix-postgres"

  ansible.builtin.set_fact:
    matrix_bot_buscarron_database_hostname: '{{ matrix_synapse_database_host }}'
    matrix_bot_buscarron_database_port: '{{ matrix_synapse_database_port }}'    


- name: Optimize DB of bot-honoroit
  when: matrix_bot_honoroit_database_hostname == "matrix-postgres"

  ansible.builtin.set_fact:
    matrix_bot_honoroit_database_hostname: '{{ matrix_synapse_database_host }}'
    matrix_bot_honoroit_database_port: '{{ matrix_synapse_database_port }}'    
