---
- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
      when: "run_setup | bool and matrix_bot_honoroit_enabled | bool"

    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
      when: "run_setup | bool and matrix_bot_honoroit_enabled | bool"
  tags:
    - setup-all
    - setup-bot-honoroit
    - install-all
    - install-bot-honoroit

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
      when: "run_setup | bool and not matrix_bot_honoroit_enabled | bool"
  tags:
    - setup-all
    - setup-bot-honoroit

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/k8s.yml"
  when: matrix_bot_honoroit_enabled | bool and matrix_k8s_mode | bool
  tags:
    - setup-all
    - setup-bot-honoroit
    - setup-k8s