---

- name: Fail if required settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - "matrix_appservice_webhooks_appservice_token"
    - "matrix_appservice_webhooks_homeserver_url"
    - "matrix_appservice_webhooks_homeserver_token"
    - "matrix_appservice_webhooks_id_token"
    - "matrix_appservice_webhooks_api_secret"

- name: "Fail when self building in nk8s mode"
  ansible.builtin.fail:
    msg: >-
      In Kubernetes mode it is not possible to use self build images. Please publish them within a available image registry.
  when: "matrix_k8s_mode | bool and matrix_appservice_webhooks_container_image_self_build | bool"