---
- name: Ensure matrix-nginx-proxy helm templates folder exists
  ansible.builtin.file:
    path: "{{ matrix_helm_data_path }}/templates/{{ normalizedRoleName }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- ansible.builtin.import_tasks: "roles/custom/matrix-k8s/tasks/subtasks/copy-yaml-files.yml"

- name: Find all conf.d files inside confd directory
  find:
    paths: "{{ matrix_nginx_proxy_confd_path }}"
    patterns: "*.conf"
  register: nginx_proxy_confd_files

- name: Replace container hostnames
  debug:
    msg: "{{ matrix_nginx_proxy_k8s_svc_replacements }}"

- name: Replace container names with k8s compatible names
  replace:
    path: "{{ item.path }}"
    regexp: 'set \$backend \"({{ matrix_nginx_proxy_k8s_svc_replacements | join("|") }}):'
    replace: 'set $backend "{{ matrix_k8s_resource_prefix }}-\1.{{ matrix_k8s_namespace }}.svc.cluster.local:'
  with_items: "{{ nginx_proxy_confd_files.files }}"

- name: Replace resolver ip with k8s compatible ip
  replace:
    path: "{{ item.path }}"
    regexp: '127\.0\.0\.11'
    replace: '{{ matrix_nginx_proxy_k8s_coredns_ip }}'
  with_items: "{{ nginx_proxy_confd_files.files }}"

# - name: copy matrix-synapse helm templates
#   ansible.builtin.template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ matrix_user_username }}"
#     group: "{{ matrix_user_groupname }}"
#     mode: 0660
#   with_items:
#     - { src: "{{ role_path }}/templates/k8s/configmap.yaml.j2", dest: "{{ matrix_helm_data_path }}/templates/matrix-synapse/configmap.yaml" }    
#   when: matrix_k8s_mode | bool