---
- ansible.builtin.set_fact:
    resourceName: "{{ role_name|replace('custom/','')|replace('matrix-','') }}"
    normalizedRoleName: "{{ role_name|replace('custom/','') }}"
    secret_passwords: []

- ansible.builtin.import_tasks: "roles/custom/matrix-k8s/tasks/subtasks/replace-passwords.yml"

- name: Ensure helm templates folder exists
  ansible.builtin.file:
    path: "{{ matrix_helm_data_path }}/templates/{{ normalizedRoleName }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Find all conf.d files inside confd directory
  find:
    paths: "{{ role_path }}/templates/k8s/"
    patterns: "*.yaml"
  register: k8s_helm_template_files

- name: copy helm templates
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ matrix_helm_data_path }}/templates/{{ normalizedRoleName }}/"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0660
  with_items: "{{ k8s_helm_template_files.files }}"

- name: Find all jinja2 files inside templates directory
  find:
    paths: "{{ role_path }}/templates/k8s/"
    patterns: "*.j2"
  register: k8s_helm_template_files

- name: copy helm templates
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ matrix_helm_data_path }}/templates/{{ normalizedRoleName }}/{{ item.path|basename|replace('.j2', '') }}"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0660
  with_items: "{{ k8s_helm_template_files.files }}"
