---
- name: print nested loop
  debug: msg=" ansible {{ item[0] }} on day {{ item[1] }}"
  when: matrix_k8s_configuration.passwordVariables is defined

  with_nested:
  - "{{ matrix_k8s_configuration.files.config }}"  
  - "{{ matrix_k8s_configuration.passwordVariables }}"
    
- name: "Replace passwords - Secure {{ item[0].variable }} - {{ item[1].variable }}"
  ansible.builtin.replace:
    path: "{{ matrix_base_data_path }}/{{ item[0].src }}"
    regexp: "{{ lookup('vars', item[1].variable) }}"
    replace: 'secret@@{{ item[1].variable }}@@secret'
  when: matrix_k8s_configuration.passwordVariables is defined
  with_nested:
  - "{{ matrix_k8s_configuration.files.config }}"  
  - "{{ matrix_k8s_configuration.passwordVariables }}"

- ansible.builtin.set_fact:
    secret_passwords: "{{ secret_passwords|combine({item.variable: lookup('vars', item.variable) }) }}"
  when: matrix_k8s_configuration.passwordVariables is defined
  with_items: "{{ matrix_k8s_configuration.passwordVariables }}"

- ansible.builtin.debug:
    msg: "{{ secret_passwords }}"