apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-proxy
  labels:
    app: nginx-proxy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-proxy
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-proxy
    spec:
      containers:
      - image: {{ .Values.Vars.matrix_nginx_proxy_docker_image }}
        name: {{ .Release.Name }}-nginx-proxy

        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"      
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10  
        imagePullPolicy: Always
        volumeMounts:
        - name: "nginx-confd"
          mountPath: "/etc/nginx/conf.d/"
        - name: "nginx-conf"
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
        ports:
        - containerPort: 8080
          name: http        
        - containerPort: 8448
          name: federation          

      volumes:
        - name: "nginx-confd"
          configMap:
            name: "{{ .Release.Name }}-nginx-proxy-confd"          
        - name: "nginx-conf"
          configMap:
            name: "{{ .Release.Name }}-nginx-proxy-conf"          
