---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matrix-nginx-proxy
  labels:
    role: matrix-nginx-proxy
{{ include "deployment.selector" . | indent 4 }}
spec:
  ports:
  - port: 8080
    name: http
  - port: 12080
    name: http-synapse
  clusterIP: None
  selector:
    role: matrix-nginx-proxy
{{ include "deployment.selector" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matrix-synapse-federation
  labels:
    role: matrix-nginx-proxy
{{ include "deployment.selector" . | indent 4 }}
spec:
  ports:
  - port: 8448
    name: http
  clusterIP: None
  selector:
    role: matrix-nginx-proxy
{{ include "deployment.selector" . | indent 4 }}
